### ISSUE TITLE
Geordi sets deploy user even if the command is commented out

### ISSUE THREAD

**Issue by FLeinzi** [makandra/geordi#110]
Hello,

I recently had the issue that I couldn't connect to an app server via `geordi shell`, because geordi tried to connect as the wrong user.

My config looked as follows:
```
# config/deploy.rb
set :application, 'some-application'
...
# set :user, 'deploy-some-application_s'
```
```
# config/deploy/staging.rb
set :stage, :staging

server 'app.some-server.com', user: 'deploy-some-application_s', roles: %w(app web cron db) 
```
```
# config/deploy/production.rb
set :stage, :production

server 'app.some-server.com', user: 'deploy-some-application_p', roles: %w(app web cron db) 
```

When I executed `geordi shell staging` everything was fine, but when I executed `geordi shell production` then I had no permission.

The reason was that geordi parsed the part `set :user, 'deploy-some-application_s'` from the `deploy.rb` and tried to connect as `deploy-some-application_s` to production. Although that line was commented out.

I think that is not intented and should be fixed.

**Comment by denzelem** [comment]
@FLeinzi Thanks for reporting the issue. I will discuss this issue with @codener. From my point of view I'm not sure if we want to handle this issue. As geordi only parses the files with a regex there a million ways how you can break it. So one could argue, that geordi only works if you have a deploy config like geordi wants it.

**Comment by makmarius** [comment]
Another idea we had when we found this was is this: currently geordi prefers the more general configuration instead of the more specific.

I found this to be surprising and unexpected as I think the more specific config should be preferred should there be one available. 

I think - if I understood the parsing code correctly - the config in `deploy.rb` is checked first and then possible more specific stuff like `staging.rb` are checked. I am not sure if it is simple to reverse the logic there though.

**Comment by denzelem** [comment]
@makmarius True, sounds strange fro me, too :smile:. c4a2f219291b7b7f346be0a8724c292b580b1392 blames me, where I actually wanted to implement exactly what you desire. Maybe its a bug, because https://github.com/makandra/geordi/blob/c4a2f219291b7b7f346be0a8724c292b580b1392/lib/geordi/capistrano_config.rb#L44-L53 seems to put the stage config before the general config correctly. I will have a closer look at this soon, when I feel ready for the regex to hell in the capistrano class :nerd_face:

**Comment by denzelem** [comment]
>  I think the more specific config should be preferred should there be one available

I looked this up. Geordi prefers the e.g. `config/deploy/staging.rb` settings over `config/deploy.rb`. But it does not work well, when you define your user as argument for the server DSL (Some Capistrano 2 / 3 thing, where Geordi needs to support both).

You can fix it by:

* Removing the comment in the `config/deploy.rb`
* Adjusting your `config/deploy/staging.rb` to something like this:
  ```
  set :user,  'deploy-some-application_s'
  server 'app.some-server.com', roles: %w(app web cron db) 
  ```

You can reopen the issue if you think we should improve the Geordi Capistrano Parser. Thanks!
