### ISSUE TITLE
Missing dependency: tracker_api

### ISSUE THREAD

**Issue by makmic** [makandra/geordi#120]
Geordi has an implicit dependency to the gem `tracker_api`, which is required for the command `geordi commit`.
When executing the command without having the gem installed, you'll see an error backtrace like this:

```
	 2: from ~/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/geordi-4.2.0/lib/geordi/gitpt.rb:4:in `<class:Gitpt>'
	 1: from ~/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
~/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- tracker_api (LoadError)
```

We should `tracker_api` to the gemspec.

**Comment by makmic** [comment]
Ok, it gets weirder. Seemingly I had ` tracker_api` 1.11.0 already installed, but bundler was unable to locate a matching version of `faraday_middleware` (installed: 0.14.0 and 0.13.1).
After manually installing `faraday_middleware 1.0.0` fixes my issue. If this affects other users as well, we should consider adding `faraday_middleware 1.0.0` as a dependency as well.

**Comment by codener** [comment]
I saw this issue (loading tracker_api fails because of missing dependency) once as well. Might be needful to investigate.

However, Geordi intentionally does not include all used Gems as dependencies in order to reduce its dependency footprint for people not using the respective commands. Instead, it sports a missing dependency loading mechanism that works really well, but unfortunately fails here. https://github.com/makandra/geordi/blob/c67008023b64dd88cbbd1bed0ddb3a7b64d97e58/lib/geordi/util.rb#L12-L31

**Comment by codener** [comment]
Closing to wait if it becomes more of an issue. 

Possible solution/improvement: [use Bundler on the fly](https://bundler.io/guides/bundler_in_a_single_file_ruby_script.html).
