### ISSUE TITLE
`geordi cucumber` with headless chrome runs the headless chrome in VNC

### ISSUE THREAD

**Issue by judithroth** [makandra/geordi#149]
Is this a known issue? I saw it in two projects, one is configured exactly as described here: https://makandracards.com/makandra/492109-capybara-running-tests-with-headless-chrome

My expectation would have been that geordi is smart enough not to use VNC if the config uses headless chrome. As geordi does other useful things, like running tests in parallel, I still would like to use `g cu` :)

Geordi 5.4.0

**Comment by denzelem** [comment]
This is the expected behavior. The card also includes the hint, that you need to manually set the following config in your project's `.geordi.yml` to disable the VNC wrapper:

```
use_vnc: false
```

> My expectation would have been that geordi is smart enough not to use VNC if the config uses headless chrome.

Geordi can not determine whether a projects uses a headless Chrome or not. Note that VNC will be removed from geordi in a feature version completely.

**Comment by judithroth** [comment]
Thanks a lot for the hint to the `.geordi.yml` setting :) of course it's working with that.
