### ISSUE TITLE
Allow arguments for `geordi tests`

### ISSUE THREAD

**Issue by makmic** [makandra/geordi#152]
During local development I find myself running single specs and features in high frequency. Too often it then happens that I run `geordi rspec features/frontend/foo.feature`. The Rspec parser obviously can't parse the feature file and I have to remind myself to run the command again with `geordi cucumber` after wondering for a moment about the failing test.

I would love if `geordi test(s)` could capsulate the test-runner decision for me. So, I'd suggest:
* `geordi tests` still runs the entire test suite
* `geordi tests path/to/spec.rb` runs the test with Rspec (or TestUnit, whatever is bundled)
* `geordi tests path/to/test.feature` runs the test with Cucumber
* Bonus:  `geordi tests path/to/spec.rb path/to/test.feature` works as well

What do you think?

**Comment by codener** [comment]
I always wanted this, but never took the time. You're welcome to submit a PR.

---

Btw, Geordi will natively recognize commands by their unique prefix, i.e. `geordi test path/to/spec.rb` is the same as the one with `tests` and has nicer semantics.

**Comment by codener** [comment]
We discussed this with the team and found that this feature could add a complexity that does not justify its usefulness. While it would be quite straightforward to support your examples, there are more cases to consider:

* Both RSpec and Cucumber support directories passed to them and will execute all their test files found inside. In order to decide which Framework should run, Geordi would need to inspect the directory contents.
* In the mixed form ("bonus"), Geordi would not know where to send command line --options

A simplified solution could be to only support a) execution from the project root b) without options c) at test default locations. Geordi could then partition arguments by their prefix `features/` and `spec/`, run Cucumber and RSpec accordingly, and print a warning for any unsupported arguments (like tests in other directories, or command line options).

However, rather than taking away from "having to think", this would add to it: for simple cases, `geordi test $files` could be used, but anything special (like starting a test from a sub directory, passing options) would only work with `geordi cucumber` or `geordi rspec`, respectively. In conclusion, we do not suggest to add this.

wdyt?

**Comment by makmic** [comment]
Thank you for looking into my feature request. I had not considered the mentioned issues, but I'm still convinced we can add a valuable feature while working around them:
* Lets drop the "bonus" idea as it leads to undefined behavior (regarding CLI options)
* I further suggest to make the new command as "dumb" as possible, it should only scan the arguments for the prefixes `features` or `spec` and relay them accordingly ("all or nothing"). Further arguments and CLI options are not attempted to be parsed and are just passed to `geordi cuc` or `geordi rspec`.

```
`geordi tests` # As usual
`geordi tests spec/frontend -b` # Same as `geordi rspec spec/frontend -b`
`geordi tests features/frontend -d` # Same as `geordi cucumber features/frontend -b`
```

**Comment by codener** [comment]
We like this simplification! Will take care of this and get back to you.
