### ISSUE TITLE
Speed up "geordi commit"

### ISSUE THREAD

**Issue by codener** [makandra/geordi#156]
Geordi commit fetches story names from Pivotal Tracker and offers them for selection of a commit title. However, currently each story name seems to be requested separately. Taking more than one second, the process becomes really slow when there are ten or more stories to fetch.

There must be a way to retrieve story names faster, it should be possible in a single request.

**Comment by brunosedler** [comment]
I took a look at this and the problem is not that each story is requested separately, but currently we request the owner of each story with a single request, thus, the more stories you have, the more requests are sent. 

When we request stories, we only get the id of the owner. But we could speed up the process by requesting all members for a project once and then find the owner by his or her id from that list.
