### ISSUE TITLE
Add Spring support

### ISSUE THREAD

**Issue by thomasklemm** [makandra/geordi#3]
It would be great if `rs` were to run `spring rspec` if available. What do you think?

**Comment by codener** [comment]
@foobear are you using `bin/rspec` with Spring? Would you judge adding this to Geordi brings a reasonable speed-up in development?

**Comment by foobear** [comment]
I do use `bin/rspec` for single files, just because the Spring binstub boots faster.

However, integrating Spring with parallel_tests is painful and I've failed to do it for complex setups. For a full (parallel) test run I don't care about Boot-up times.

So maybe use `bin/rspec` when given a set of files, but not when called without arguments? :thinking:
