### ISSUE TITLE
`geordi cucumber` ignores directory set in the parallel profile and uses `features/` instead.

### ISSUE THREAD

**Issue by judithroth** [makandra/geordi#50]
In `cucumber.yml` you can define defaults for different profiles, e.g.

```
parallel: --format progress --format ParallelTests::Cucumber::FailuresLogger --out tmp/cucumber_failures.log app/wizards
```

I appended a different directory because I have to run features outside of of the `features/` directory.
Although `geordi cucumber` claims to be using the parallel profile it still runs the features in the `features/` directory instead of the ones in `app/wizards`.

I guess the problem is this line: https://github.com/makandra/geordi/blob/eeeb79d3b0a684c82a6b37e4811844a64d63ff47/lib/geordi/commands/cucumber.rb#L75

Although using the features-directory is a good default, geordi should first check if there are different directories mentioned in the profile and use them if given.

**Comment by denzelem** [comment]
@judithroth This seems like an issue with `parallel_test` and not `geordi` itself. I couldn't find a way how to skip passing in files or a directory to  `parallel_test`, so that the file options from the parallel profile are used.

The CLI validation happens [before](https://github.com/grosser/parallel_tests/blob/9bf7d525bd4a6d9865e3664d95dd670c6ab76b73/lib/parallel_tests/cli.rb#L241) the parallel profile is [read](https://github.com/grosser/parallel_tests/blob/1a2f4c3561871d63f47a70501af0924a84f24cf2/lib/parallel_tests/gherkin/runner.rb#L25). Therefore the [documentation](https://github.com/grosser/parallel_tests/tree/e96a0e1bdcad98a614cc4da448c4c9ffe491d917#cucumber-failureslogger) shows an example with options only. 

```
bundle exec parallel_test -t cucumber
Pass files or folders to run
```

Cucumber itself seems to support this [feature](https://github.com/cucumber/cucumber-rails/blob/23e141c220cfd68b5ea8ce1872ad8fb10bf12c27/config/cucumber.yml). It somehow checks the `cucumber.yml` first and then uses `features` as fallback. Maybe this is the reasons why it was expected to be supported by `parallel_tests`, too.

**Comment by judithroth** [comment]
Thanks for the investigation!
