### ISSUE TITLE
Make geordi aware of a headless Chrome driver

### ISSUE THREAD

**Issue by denzelem** [makandra/geordi#91]
For current projects we don't use VNC anymore and use a headless Chrome instead. This makes it easier to interact with the Chrome window when debugging and removes one layer from the stack. 

It would be nice (imho) if Geordi does not wrap a headless Chrome in a VNC window. Projects with a headless Chrome define a tag `@no-headless` to start the Chrome visible for the user.

Can we detect if Geordi should use VNC or not easily? @codener @kratob @triskweline

**Comment by kratob** [comment]
I don't see a reliable way to do that. Obviously one could grep for the existence of the `@no-headless` tag or similar, but that seems very hacky.

We could introduce something like a `.geordi` file where it is possible to configure things like this.

In practise I don't think it's a big deal. When I'm working on a project with a headless chrome I will always use `bin/cucumber` to run single features anyways, since the startup is much faster. For a full test run it does not matter too much whether we redirect output to VNC.

**Comment by denzelem** [comment]
We decided to have a project specific `.geordi.yml` file that contains this information. With this change the following settings could be improved:

* The `.pt_project_id` in der project directory is merged into the `.geordi.yml` file
* The `.gitpt` and the settings for the db drop command are merged in `~/.config/geordi/global.yml`
* We create a new settings class, that take care of handling old and new paths.
  * For the global settings we make an automatic migration
  * For the local settings we ask the user to apply the migration. Maybe with an prompt, so the diff in the git repository is not unexpected.

Any opinions on this?

**Comment by denzelem** [comment]
After a short discussion, we decided to to just show a deprecation warning if a `.pt_project_id` file is present. The `.pt_project_id` file is ignored completely and we just use `.geordi.yml` in the new major release of geordi. Global options are not adjusted for now.
